blueprint:
  name: Template sensor to store alert data
  description: >
    ![Image](https://github.com/TheFes/ha-blueprints/blob/main/images/TheFesCasa_logo_bp_light.png?raw=true)

    # 🚨 Alert data sensor

    This blueprint helps you create a template sensor which stores the data of active alert automations created using the [Telegram alert blueprint](/telegram/telegram_alert.md).


    By using this template sensor alerts can be continued after a restart of HA or reload of the alert automation. If the sensor is not used the alert will start over from scratch then.
    
    The alert automation also has functionality to remove old messages from the Telegram chat, which will only work for messages sent before a HA restart or auotomation reload in case this sesnor is used.


    ## ❓ How to use

    For more information how to import and use it, see the [documentation](<https://github.com/TheFes/ha-blueprints/blob/main/other/alert_data_sensor.md>).


    ## ☕ Coffee

    If you think I deserve a coffe, please feel free to buy me one (I might spend it on another beverage though).

    In case you decide to do so, thanks a lot!

    <a href="https://www.buymeacoffee.com/thefes" target="_blank">![Buy Me A Coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)</a>


    Or you can do a small donation using PayPal.

    [![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/paypalme/thefes)
  author: TheFes
  source_url: https://github.com/TheFes/ha-blueprints/blob/main/other/alert_data_sensor.yaml
  domain: template
  input:
    optional_settings:
      name: Optional settings
      icon: mdi:cog
      description:
        Optional settings to change the default entity id or the event on which it triggers

        In case you change these, make sure to update it in the automations created with the Alert blueprint as well
      collapsed: true
      input:
        trigger_event:
          name: Trigger event
          description: The manual event type on which the sensor will trigger
          selector:
            text:
          default: update_thefes_alert_sensor
        entity_id:
          name: Entity id
          description: The entity id which will be used for this template sensor

            If you change the entity in the GUI after the template sensor is created, make sure to update it here as well
            otherwise the sensor will no longer work.
          selector:
            text:
          default: sensor.thefes_alert_data
triggers:
  - alias: Trigger on the manual event
    trigger: event
    event_type: !input trigger_event
variables:
  entity_id: !input entity_id
  current_data: "{{ state_attr(entity_id, 'alert_data') | default({}, true) }}"
  new_data: "{{ trigger.event.data.alert_data }}"
  combined_data: >
    {{
        current_data | combine(new_data)
        if current_data is mapping
          and new_data is mapping
        else current_data
    }}
sensor:
  default_entity_id: !input entity_id
  state: "{{ combined_data.values() | select() | list | count }}"
  device_class: current
  unit_of_measurement: A
  attributes:
    alert_data: "{{ combined_data }}"
